# Generated by Django 5.0 on 2024-01-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_profile_is_public_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlevel',
            name='title',
            field=models.CharField(null=True),
        ),
    ]
