# Generated by Django 5.0 on 2024-01-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_subscriptionlevel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionlevel',
            name='title',
            field=models.CharField(default='x'),
            preserve_default=False,
        ),
    ]
