# Generated by Django 5.0 on 2024-01-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_item_price_outfitpost_picture_outfitpost_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitpost',
            name='picture',
            field=models.ImageField(default='images/outfits/default.png', upload_to='images/outfits/'),
            preserve_default=False,
        ),
    ]
