# Generated by Django 5.0 on 2024-01-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_outfitpost_description_outfitpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='style_tags',
            field=models.ManyToManyField(to='API.styletag'),
        ),
        migrations.AddField(
            model_name='outfitpost',
            name='style_tags',
            field=models.ManyToManyField(to='API.styletag'),
        ),
    ]
